architecture: deepspeech2
use_bidirectional: True
hidden_dim: 1024
dropout: 0.3
num_encoder_layers: 3
rnn_type: gru
max_len: 400
activation: hardtanh
teacher_forcing_ratio: 1.0
teacher_forcing_step: 0.0
min_teacher_forcing_ratio: 1.0
joint_ctc_attention: false